<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ReqnrollFeatureFile Remove="Features\FileDownload.feature" />
    <ReqnrollFeatureFile Remove="Features\GlobalSearch.feature" />
    <ReqnrollFeatureFile Remove="Features\InsightsCarousel.feature" />
    <ReqnrollFeatureFile Remove="Features\JobSearch.feature" />
    <ReqnrollFeatureFile Remove="Features\Services.feature" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Reqnroll.xUnit" Version="3.3.4" />
    <PackageReference Include="xunit" Version="2.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLayer\BusinessLayer.csproj" />
    <ProjectReference Include="..\CoreLayer\CoreLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
